FROM java:8-alpine
MAINTAINER crazyquark

RUN mkdir -p /opt/cakeshop
WORKDIR /opt/cakeshop

RUN apk update && \
 apk add ca-certificates wget && \
 update-ca-certificates

RUN wget https://github.com/jpmorganchase/cakeshop/releases/download/0.9.1/cakeshop-0.9.1-x86_64-linux.war -O cakeshop.war

ENTRYPOINT java -jar cakeshop.war
